export const content = new Object();

content['DepilacionConHilo'] = [
  {
    title: 'VIDEO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
];

content['DisenoDeCejas'] = [
  {
    title: 'VIDEO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
];

content['Pestanas'] = [
  {
    title: 'VIDEO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
];

content['Micropigmentacion'] = [
  {
    title: 'VIDEO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
];

content['BrowLamination'] = [
  {
    title: 'VIDEO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'video',
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: 'VIDEO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: 'video',
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
];
