export const content = new Object();


content["DepilacionConHilo"] = [
  {
    title: "FOTO 1",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: "video",
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 2",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: "video",
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 3",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: "video",
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 4",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: "video",
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 5",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: "video",
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
];

content["DisenoDeCejas"] = [
  {
    title: "FOTO 1",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: "video",
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 2",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: "video",
    background: require('../../../images/bgpadrao.png'),
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 3",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: "video",
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 4",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: "video",
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
  {
    title: "FOTO 5",
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    background: require('../../../images/bgpadrao.png'),
    mediaType: "video",
    viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
  },
];

content["Pestanas"] = [
{
  title: "FOTO 1",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  mediaType: "video",
  background: require('../../../images/bgpadrao.png'),
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 2",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  mediaType: "video",
  background: require('../../../images/bgpadrao.png'),
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 3",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 4",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 5",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
];

content["Micropigmentacion"] = [
{
  title: "FOTO 1",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  mediaType: "video",
  background: require('../../../images/bgpadrao.png'),
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 2",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  mediaType: "video",
  background: require('../../../images/bgpadrao.png'),
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 3",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 4",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 5",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
];

content["Microblading"] = [
{
  title: "FOTO 1",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  mediaType: "video",
  background: require('../../../images/bgpadrao.png'),
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 2",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  mediaType: "video",
  background: require('../../../images/bgpadrao.png'),
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 3",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 4",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
{
  title: "FOTO 5",
  textSummary: `Lorem ipsum`,
  textContent: `Lorem ipsum dolor sit amet`,
  background: require('../../../images/bgpadrao.png'),
  mediaType: "video",
  viewSrc: require('../../../videos/Tamara_videoInicial_01_original_sierra.mp4'),
},
];
