export const content = new Object();

content['DepilacionConHilo'] = [
  {
    title: 'FOTO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/DepilacionConHilo/new001/_MG_4835.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/DepilacionConHilo/new001/_MG_4835.jpg'),
  },
  {
    title: 'FOTO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/DepilacionConHilo/new001/_MG_4849.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/DepilacionConHilo/new001/_MG_4849.jpg'),
  },
  {
    title: 'FOTO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/DepilacionConHilo/new001/_MG_4924.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/DepilacionConHilo/new001/_MG_4924.jpg'),
  },
];

content['DisenoDeCejas'] = [
  {
    title: 'FOTO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/Visagismo/new002/_MG_4751.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/Visagismo/new002/_MG_4751.jpg'),
  },
  {
    title: 'FOTO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/Visagismo/new002/_MG_4782.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/Visagismo/new002/_MG_4782.jpg'),
  },
  {
    title: 'FOTO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/Visagismo/new002/_MG_4918.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/Visagismo/new002/_MG_4918.jpg'),
  },
];

content['Pestanas'] = [
  {
    title: 'FOTO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/LashLifting/new001/20190909_153023.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/LashLifting/new001/20190909_153023.jpg'),
  },
  {
    title: 'FOTO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/LashLifting/new001/20200713_144046.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/LashLifting/new001/20200713_144046.jpg'),
  },
  {
    title: 'FOTO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/LashLifting/new001/PicsArt_03-01-04.31.10.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/LashLifting/new001/PicsArt_03-01-04.31.10.jpg'),
  },
  {
    title: 'FOTO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/LashLifting/new002/TF_LashLiftingPro_09dez2018_179.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/LashLifting/new002/TF_LashLiftingPro_09dez2018_179.jpg'),
  },
  {
    title: 'FOTO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/LashLifting/new002/TF_LashLiftingPro_09dez2018_190.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/LashLifting/new002/TF_LashLiftingPro_09dez2018_190.jpg'),
  },
  {
    title: 'FOTO 6',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/LashLifting/new002/TF_LashLiftingPro_09dez2018_198.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/LashLifting/new002/TF_LashLiftingPro_09dez2018_198.jpg'),
  },
];

content['Micropigmentacion'] = [
  {
    title: 'FOTO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroCejas/new001/04ACABA0-F76E-47EE-B886-59AD8CCA8FAC.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroCejas/new001/04ACABA0-F76E-47EE-B886-59AD8CCA8FAC.jpeg'),
  },
  {
    title: 'FOTO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroCejas/new001/20201002_145329.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroCejas/new001/20201002_145329.jpg'),
  },
  {
    title: 'FOTO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroCejas/new001/F58B4F2B-A66A-428C-92FC-5FB919D39911.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroCejas/new001/F58B4F2B-A66A-428C-92FC-5FB919D39911.jpeg'),
  },
  {
    title: 'FOTO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroEyeliner/new001/20200612_161032.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroEyeliner/new001/20200612_161032.jpg'),
  },
  {
    title: 'FOTO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroEyeliner/new001/IMG_7114.JPG'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroEyeliner/new001/IMG_7114.JPG'),
  },
  {
    title: 'FOTO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroLabios/new001/09E15196-248D-43A6-8856-FC5D1DE10406_inclinado.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroLabios/new001/09E15196-248D-43A6-8856-FC5D1DE10406_inclinado.jpeg'),
  },
  {
    title: 'FOTO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroLabios/new001/09E15196-248D-43A6-8856-FC5D1DE10406_reto.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroLabios/new001/09E15196-248D-43A6-8856-FC5D1DE10406_reto.jpeg'),
  },
  {
    title: 'FOTO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroLabios/new001/20191101_180718.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroLabios/new001/20191101_180718.jpg'),
  },
  {
    title: 'FOTO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroLabios/new001/84BC588F-0D4A-4B83-8D63-4BBE275A48B4.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroLabios/new001/84BC588F-0D4A-4B83-8D63-4BBE275A48B4.jpeg'),
  },
  {
    title: 'FOTO 5',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/MicroLabios/new001/PicsArt_06-25-04.43.32.jpg'),
    viewSrc: require('../../../images/pictures/procedimientos/MicroLabios/new001/PicsArt_06-25-04.43.32.jpg'),
  },
];

content['BrowLamination'] = [
  {
    title: 'FOTO 1',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/425CADC0-66C0-4250-BA5D-2120D1C77965.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/425CADC0-66C0-4250-BA5D-2120D1C77965.jpeg'),
  },
  {
    title: 'FOTO 2',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/58E84822-DF47-4713-9CA1-53A9B4861513.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/58E84822-DF47-4713-9CA1-53A9B4861513.jpeg'),
  },
  {
    title: 'FOTO 3',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/E9D5B3DB-E81F-4DE7-9F7C-BCBEDD19E3EA.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/E9D5B3DB-E81F-4DE7-9F7C-BCBEDD19E3EA.jpeg'),
  },
  {
    title: 'FOTO 4',
    textSummary: `Lorem ipsum`,
    textContent: `Lorem ipsum dolor sit amet`,
    mediaType: 'image',
    background: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/FB1B87D6-7265-4A83-8710-99F331ECE7CF.jpeg'),
    viewSrc: require('../../../images/pictures/procedimientos/BrowLamination/new001/AntesDepois/FB1B87D6-7265-4A83-8710-99F331ECE7CF.jpeg'),
  },
];
